"""Pydantic schemas for MIDA API."""

from app.schemas.mida_certificate import (
    CertificateItemIn,
    CertificateHeaderIn,
    CertificateDraftCreateRequest,
    CertificateDraftUpdateRequest,
    CertificateRead,
    CertificateItemRead,
    CertificateListResponse,
)

from app.schemas.convert import (
    ConversionWarning,
    ConvertRequest,
    ConvertResponse,
    InvoiceItemBase,
    MatchMode,
    MidaMatchedItem,
    WarningSeverity,
)

from app.schemas.mida_import import (
    ImportPort,
    QuantityStatus,
    ImportRecordCreate,
    ImportRecordBulkCreate,
    ImportRecordRead,
    ImportRecordWithContext,
    ImportRecordListResponse,
    ItemBalanceRead,
    ItemBalanceUpdate,
    ItemBalanceListResponse,
    ItemWarning,
    WarningStatusResponse,
    ImportHistoryQuery,
    ImportHistoryResponse,
    PortSummary,
    PortSummaryResponse,
    SettingRead,
    SettingUpdate,
    DefaultThresholdUpdate,
    ImportPreview,
    ImportPreviewResponse,
)

__all__ = [
    # MIDA Certificate schemas
    "CertificateItemIn",
    "CertificateHeaderIn",
    "CertificateDraftCreateRequest",
    "CertificateDraftUpdateRequest",
    "CertificateRead",
    "CertificateItemRead",
    "CertificateListResponse",
    # Convert schemas
    "ConversionWarning",
    "ConvertRequest",
    "ConvertResponse",
    "InvoiceItemBase",
    "MatchMode",
    "MidaMatchedItem",
    "WarningSeverity",
    # Import tracking schemas
    "ImportPort",
    "QuantityStatus",
    "ImportRecordCreate",
    "ImportRecordBulkCreate",
    "ImportRecordRead",
    "ImportRecordWithContext",
    "ImportRecordListResponse",
    "ItemBalanceRead",
    "ItemBalanceUpdate",
    "ItemBalanceListResponse",
    "ItemWarning",
    "WarningStatusResponse",
    "ImportHistoryQuery",
    "ImportHistoryResponse",
    "PortSummary",
    "PortSummaryResponse",
    "SettingRead",
    "SettingUpdate",
    "DefaultThresholdUpdate",
    "ImportPreview",
    "ImportPreviewResponse",
]
