#!/bin/bash
# =============================================================================
# MIDA OCR Application - Setup Wizard
# =============================================================================
# Interactive setup script for production deployment
# Run this script on the server to configure the application
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Print colored output
print_header() {
    echo -e "\n${BLUE}============================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}============================================${NC}\n"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

# Check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_warning "This script should be run as root or with sudo for full functionality"
    fi
}

# Check Docker installation
check_docker() {
    print_header "Checking Docker Installation"
    
    if command -v docker &> /dev/null; then
        print_success "Docker is installed: $(docker --version)"
    else
        print_error "Docker is not installed!"
        echo "Please install Docker first: https://docs.docker.com/engine/install/"
        exit 1
    fi
    
    if command -v docker-compose &> /dev/null || docker compose version &> /dev/null; then
        print_success "Docker Compose is available"
    else
        print_error "Docker Compose is not installed!"
        exit 1
    fi
    
    # Check if Docker daemon is running
    if docker info &> /dev/null; then
        print_success "Docker daemon is running"
    else
        print_error "Docker daemon is not running!"
        echo "Try: sudo systemctl start docker"
        exit 1
    fi
}

# Generate secure random password
generate_password() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24
}

# Create .env file
create_env_file() {
    print_header "Environment Configuration"
    
    ENV_FILE=".env"
    
    if [ -f "$ENV_FILE" ]; then
        print_warning ".env file already exists!"
        read -p "Do you want to overwrite it? (y/N): " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            print_info "Keeping existing .env file"
            return
        fi
        cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
        print_info "Backup created"
    fi
    
    echo ""
    echo "Please provide the following configuration values:"
    echo ""
    
    # Azure Document Intelligence
    print_info "Azure Document Intelligence Configuration"
    echo "Get these from Azure Portal > Document Intelligence > Keys and Endpoint"
    echo ""
    read -p "Azure DI Endpoint URL: " azure_endpoint
    read -p "Azure DI API Key: " azure_key
    
    # Validate Azure endpoint format
    if [[ ! "$azure_endpoint" =~ ^https:// ]]; then
        print_warning "Endpoint should start with https://"
    fi
    
    # Database configuration
    echo ""
    print_info "Database Configuration"
    read -p "Database username [mida]: " db_user
    db_user=${db_user:-mida}
    
    read -p "Database name [mida]: " db_name
    db_name=${db_name:-mida}
    
    default_password=$(generate_password)
    read -p "Database password [auto-generated]: " db_password
    db_password=${db_password:-$default_password}
    
    # Server configuration
    echo ""
    print_info "Server Configuration"
    read -p "Frontend port [80]: " frontend_port
    frontend_port=${frontend_port:-80}
    
    read -p "API port [8000]: " api_port
    api_port=${api_port:-8000}
    
    read -p "Number of API workers [4]: " workers
    workers=${workers:-4}
    
    # CORS configuration
    echo ""
    print_info "CORS Configuration"
    echo "Enter allowed origins (comma-separated)"
    echo "Example: http://localhost,https://your-domain.com"
    read -p "CORS origins [http://localhost]: " cors_origins
    cors_origins=${cors_origins:-http://localhost}
    
    # Backup configuration
    echo ""
    print_info "Backup Configuration"
    read -p "Backup retention days [7]: " backup_days
    backup_days=${backup_days:-7}
    
    # Create .env file
    cat > "$ENV_FILE" << EOF
# =============================================================================
# MIDA OCR Application - Production Environment
# =============================================================================
# Generated by setup wizard on $(date)
# =============================================================================

# === Azure Document Intelligence ===
AZURE_DI_ENDPOINT=${azure_endpoint}
AZURE_DI_KEY=${azure_key}

# === Database ===
POSTGRES_USER=${db_user}
POSTGRES_PASSWORD=${db_password}
POSTGRES_DB=${db_name}

# === Application ===
ENVIRONMENT=production
DEBUG=false
LOG_LEVEL=INFO
LOG_FORMAT=json

# === Server ===
API_PORT=${api_port}
FRONTEND_PORT=${frontend_port}
WORKERS=${workers}

# === CORS ===
CORS_ORIGINS=${cors_origins}

# === Backups ===
BACKUP_RETENTION_DAYS=${backup_days}
EOF

    chmod 600 "$ENV_FILE"
    print_success ".env file created successfully"
    print_warning "Database password: ${db_password}"
    echo "Please save this password securely!"
}

# Create required directories
create_directories() {
    print_header "Creating Required Directories"
    
    mkdir -p backups
    mkdir -p logs
    
    print_success "Created backups/ directory"
    print_success "Created logs/ directory"
}

# Build Docker images
build_images() {
    print_header "Building Docker Images"
    
    print_info "Building backend image..."
    docker compose build mida-api
    print_success "Backend image built"
    
    print_info "Building frontend image..."
    docker compose build mida-frontend
    print_success "Frontend image built"
}

# Run database migrations
run_migrations() {
    print_header "Running Database Migrations"
    
    print_info "Starting database container..."
    docker compose up -d postgres
    
    print_info "Waiting for database to be ready..."
    sleep 10
    
    print_info "Running Alembic migrations..."
    docker compose run --rm db-migrate
    
    print_success "Database migrations completed"
}

# Start all services
start_services() {
    print_header "Starting Services"
    
    docker compose up -d mida-api mida-frontend db-backup
    
    print_info "Waiting for services to start..."
    sleep 5
    
    # Check health
    if docker compose ps | grep -q "healthy"; then
        print_success "Services are running and healthy"
    else
        print_warning "Services are starting... checking health"
        sleep 10
        docker compose ps
    fi
}

# Display final information
show_summary() {
    print_header "Setup Complete!"
    
    # Get frontend port from .env
    source .env 2>/dev/null || true
    frontend_port=${FRONTEND_PORT:-80}
    api_port=${API_PORT:-8000}
    
    echo "Your MIDA OCR application is now running!"
    echo ""
    echo "Access URLs:"
    echo "  Frontend:  http://$(hostname -I | awk '{print $1}'):${frontend_port}"
    echo "  API:       http://$(hostname -I | awk '{print $1}'):${api_port}"
    echo "  API Docs:  http://$(hostname -I | awk '{print $1}'):${api_port}/docs"
    echo ""
    echo "Useful commands:"
    echo "  View logs:           docker compose logs -f"
    echo "  Stop services:       docker compose down"
    echo "  Restart services:    docker compose restart"
    echo "  View status:         docker compose ps"
    echo "  Manual backup:       docker compose exec db-backup /run-backup.sh"
    echo ""
    print_info "Backups are stored in ./backups/ and run daily at 2 AM"
    print_info "Logs are rotated automatically by Docker"
}

# Main menu
main_menu() {
    print_header "MIDA OCR Application Setup Wizard"
    
    echo "What would you like to do?"
    echo ""
    echo "1) Full setup (recommended for first-time deployment)"
    echo "2) Configure environment only"
    echo "3) Build Docker images only"
    echo "4) Run database migrations only"
    echo "5) Start/restart services"
    echo "6) Show status"
    echo "7) Exit"
    echo ""
    read -p "Select option [1]: " choice
    choice=${choice:-1}
    
    case $choice in
        1)
            check_docker
            create_directories
            create_env_file
            build_images
            run_migrations
            start_services
            show_summary
            ;;
        2)
            create_env_file
            ;;
        3)
            check_docker
            build_images
            ;;
        4)
            check_docker
            run_migrations
            ;;
        5)
            check_docker
            start_services
            show_summary
            ;;
        6)
            docker compose ps
            ;;
        7)
            echo "Goodbye!"
            exit 0
            ;;
        *)
            print_error "Invalid option"
            exit 1
            ;;
    esac
}

# Run main menu
check_root
main_menu
